Update checkstyle_checks.xml
jcalhounn/Software-Engineering-Project pull request #9
Opened 2024-02-11 22:03 UTC by taylorpitman

Wanted to adjust indentation and we had double modules for left and right curly brackets

2024-02-11 22:10 UTC, taylorpitman commented
theres a missing module at the end of the file

2024-02-11 23:49 UTC, jcalhounn requested changes
add </module> back at the end

2024-02-11 23:49 UTC, jcalhounn commented on checkstyle_checks.xml
> -  </module>
this shouldnt of been deleted, we need to add it back

2024-02-12 00:01 UTC, jcalhounn approved these changes

2024-02-12 00:01 UTC, merged